// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe24tqN01QTXEEWe8x86K7xBf6m0OmQGo',
    appId: '1:838732447019:web:e87d2a9f3e4599952e996e',
    messagingSenderId: '838732447019',
    projectId: 'realpokergamedb',
    authDomain: 'realpokergamedb.firebaseapp.com',
    storageBucket: 'realpokergamedb.appspot.com',
    measurementId: 'G-W6J12Q4VTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo7aSRiTJ2lEkF24wvFPbejsNTtXJjQaU',
    appId: '1:838732447019:android:d0d71e72d87938be2e996e',
    messagingSenderId: '838732447019',
    projectId: 'realpokergamedb',
    storageBucket: 'realpokergamedb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm8SQ6sul7-0eO9THDCH_y1YHJinBJwtk',
    appId: '1:838732447019:ios:fda644dca53ac8d92e996e',
    messagingSenderId: '838732447019',
    projectId: 'realpokergamedb',
    storageBucket: 'realpokergamedb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm8SQ6sul7-0eO9THDCH_y1YHJinBJwtk',
    appId: '1:838732447019:ios:fda644dca53ac8d92e996e',
    messagingSenderId: '838732447019',
    projectId: 'realpokergamedb',
    storageBucket: 'realpokergamedb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe24tqN01QTXEEWe8x86K7xBf6m0OmQGo',
    appId: '1:838732447019:web:70c4f3b51151bb242e996e',
    messagingSenderId: '838732447019',
    projectId: 'realpokergamedb',
    authDomain: 'realpokergamedb.firebaseapp.com',
    storageBucket: 'realpokergamedb.appspot.com',
    measurementId: 'G-JCMF1BMBBR',
  );

}